# Alacritty Terminal Configuration - Gruvbox Dark Theme
# Cross-platform terminal configuration for Catred Config
# Font Configuration
font:
  normal:
    family: "JetBrains Mono Nerd Font"
    style: Regular
  bold:
    family: "JetBrains Mono Nerd Font"
    style: Bold
  italic:
    family: "JetBrains Mono Nerd Font"
    style: Italic
  bold_italic:
    family: "JetBrains Mono Nerd Font"
    style: Bold Italic
  size: 12
# Window Configuration
window:
  padding:
    x: 8
    y: 8
  dynamic_padding: false
  decorations: full
  opacity: 1.0
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true
# Scrolling
scrolling:
  history: 10000
  multiplier: 3
# Colors - Gruvbox Dark
colors:
  primary:
    background: '#282828'
    foreground: '#ebdbb2'
  cursor:
    text: '#282828'
    cursor: '#d79921'
  selection:
    text: '#282828'
    background: '#d5c4a1'
  normal:
    black: '#282828'
    red: '#cc241d'
    green: '#98971a'
    yellow: '#d79921'
    blue: '#458588'
    magenta: '#b16286'
    cyan: '#689d6a'
    white: '#a89984'
  bright:
    black: '#928374'
    red: '#fb4934'
    green: '#b8bb26'
    yellow: '#fabd2f'
    blue: '#83a598'
    magenta: '#d3869b'
    cyan: '#8ec07c'
    white: '#ebdbb2'
# Bell
bell:
  animation: EaseOutExpo
  duration: 0
  color: '#d79921'
# Mouse
mouse:
  hide_when_typing: true
# Terminal Features
live_config_reload: true
# Shell (use default shell)
shell:
  program: /bin/bash
  args:
    - --login

