name: "Catppuccin Macchiato"
accent: "#eed49f"
background: "#24273a"
foreground: "#cad3f5"
details: "darker"
terminal_colors:
  normal:
    black: "#494d64"
    red: "#ed8796"
    green: "#a6da95"
    yellow: "#eed49f"
    blue: "#8aadf4"
    magenta: "#c6a0f6"
    cyan: "#8bd5ca"
    white: "#cad3f5"
  bright:
    black: "#5b6078"
    red: "#ed8796"
    green: "#a6da95"
    yellow: "#eed49f"
    blue: "#8aadf4"
    magenta: "#c6a0f6"
    cyan: "#8bd5ca"
    white: "#a5adcb"