name: "Tokyo Night Storm"
accent: "#e0af68"
background: "#24283b"
foreground: "#c0caf5"
details: "darker"
terminal_colors:
  normal:
    black: "#15161e"
    red: "#f7768e"
    green: "#9ece6a"
    yellow: "#e0af68"
    blue: "#7aa2f7"
    magenta: "#bb9af7"
    cyan: "#73daca"
    white: "#c0caf5"
  bright:
    black: "#414868"
    red: "#f7768e"
    green: "#9ece6a"
    yellow: "#e0af68"
    blue: "#7aa2f7"
    magenta: "#bb9af7"
    cyan: "#7dcfff"
    white: "#c0caf5"
